Repository AleGodoy12/Staffing, pull requests merged in 2023-08, with the labels that each got.

#1 Add description of project into README.md
  README.md
Labels: documentation

#2 Create technicalREADME.md
  technicalREADME.md
Labels: documentation

#3 Setup backend with express and dotenv
  server/.gitignore
  server/app.js
  server/bin/www
  server/package-lock.json
  server/package.json
Labels: enhancement

#8 Update technicalREADME.md
  technicalREADME.md
Labels: documentation

#9 Login controllers, routes and validations
  .prettierrc.json
  server/app.js
  server/controllers/loginControllers.js
  server/db/database.js
  server/middlewares/validateLogin.js
  server/package-lock.json
  server/package.json
  server/routes/loginRoutes.js
Labels: enhancement

#10 built design and configured dependency
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.jsx
  client/src/assets/css/Defaults.css
  client/src/assets/css/Login.css
  client/src/assets/fonts/Roboto-Bold.woff
  client/src/assets/fonts/Roboto-Light.woff
  client/src/assets/fonts/Roboto-Medium.woff
  client/src/assets/fonts/Roboto-Regular.woff
  client/src/assets/fonts/Rubik-Bold.woff
  client/src/assets/fonts/Rubik-Light.woff
  client/src/assets/fonts/Rubik-Medium.woff
  client/src/assets/fonts/Rubik-Regular.woff
  client/src/assets/icons/arbusta-icon.png
  client/src/assets/images/bg-login-desktop.png
  client/src/assets/images/bg-login-mobile.png
  client/src/assets/images/bg-login-tablet.png
  client/src/assets/react.svg
  client/src/components/Login.jsx
  client/src/index.css
  client/src/main.jsx
Labels: enhancement, config

#13 Projects CRUD
  server/app.js
  server/controllers/projectControllers.js
  server/db/staffing.sql
  server/middlewares/validateProject.js
  server/routes/projectRoutes.js
Labels: enhancement, database
